bases:
  - "bases/repos.yaml"
  - "bases/environments.yaml"

helmfiles:
  - path: "releases/releases.yaml"

helmDefaults:
  atomic: true
  createNamespace: true
  cleanupOnFail: true
  verify: true
  timeout: 300
  wait: true

missingFileHandler: Error

