apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
  labels:
    app: python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: python
          image: eqtoqjwe.gra5.container-registry.ovh.net/private/loadtest:latest
          env:
            - name: WAIT_TIME
              value: "30"
          command: ["main"]
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: python-svc
  labels:
    app: python
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      protocol: TCP
  selector:
    app: python
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "620s"
    ingress.kubernetes.io/whitelist-source-range: "51.91.23.43/32"
#    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: python.marc.k8s.carmier.fr
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: python-svc
                port:
                  number: 80

