image:
  #repository: eqtoqjwe.gra5.container-registry.ovh.net/private/loadtest
  repository: k3d-registry.k3d.lan.carmier.fr:5000/loadtest
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

ingress:
  hosts:
    - host: api.gunicorn.k3d.lan.carmier.fr
      paths:
        - path: /
          pathType: Prefix

cmd: ["api"]
envs:
  - name: "WAIT_TIME"
    value: "30"
  - name: G_BACKLOG
    value: "2048"
  - name: G_TIMEOUT
    value: "0"